name: git-hub-actions-flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python
        run: |
        python -m pip install --upgrade pip
        pip install pytest
      - name: Run pytest
        run: |
        cd src
        python -m pytest addition.py
        
        
      

    
    


